version: "3.6"

networks:
  main:

volumes:
  parity:

services:
  launchpad-rb:
    build:
      context: app
    image: appliedblockchain/launchpad-rb
    hostname: launchpad-rb
    ports:
      - 3000:3000
    environment: []
    depends_on:
      - parity
      - postgres
    networks:
      - main

  postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=foobar
    image: postgres
    ports:
      - 5432:5432
    networks:
      - main
    restart: unless-stopped

  parity:
    image: appliedblockchain/parity-solo-instant
    volumes:
      - parity:/solo/chains
    networks:
      - main
    restart: unless-stopped

# get the parity setup from launchpad for non dev chains:
# https://github.com/appliedblockchain/launchpad/blob/master/docker-compose.yml
