source "http://rubygems.org"

gem "roda"

gem "digest-sha3", git: "https://github.com/izetex/digest-sha3-ruby"

gem 'ethereum.rb'

gem "rake"

gem "pg"
gem "dm-core"
gem "dm-migrations"
gem "dm-postgres-adapter"

gem "puma"
